apiVersion: v1
kind: Service
metadata:
    name: "margenpurpose-d5ac"
    labels:
        app: "margenpurpose-d5ac"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "margenpurpose-d5ac"