apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/part-of: aks-egress-checker
  name: aks-egress-checker
  namespace: kube-system
spec:
  containers:
    - image: "amargherio.azurecr.io/utils/egress-checker:0.9.0"
      command: ['aks-egress-checker']
      args:
      - audit
      imagePullPolicy: Always
      name: aks-egress-checker
      resources:
        limits:
          cpu: 250m
          memory: 384Mi
        requests:
          cpu: 100m
          memory: 128Mi
#      volumeMounts:
#        - name: egress-data
#          mountPath: /etc/egress-data
  restartPolicy: Never
#  volumes:
#    - name: egress-data
#      configMap:
#        name: egress-check-data
#        items:
#          - key: 20220315-egress
#            path: 20220315-egress.json
